pagopa/io-dev-api-server

- README.MD
- package.json
- payloads/message.ts
- payloads/wallet.ts
- src/__tests__/profile.test.ts
- src/server.ts
- src/utils/id.ts
This pr introduces mocked wallets and transactions to display in the Wallet Home of IO app.
> Add mocked wallets and transactions

- package.json
This pr apply 2 changes:
- remove the empty file "jest.config.json"
- add the rule  `"preset": "ts-jest" ` within the package file (being a short rule, I preferred to introduce it in `package.json` instead of in a `jest.config.js` file to avoid other changes to the `.gitignore` file - that currently ignore all .js files)
Without these changes, just importing the repo a half of the tests fail.
> Update jest configuration

- .dockerignore
- .github/workflows/dockerpush.yml
- Dockerfile
Creating a Github workflow to manage every push on master or a release tag creation, in order to build and publish a docker image.
> [#171514553] - Il server deve essere disponibile come immagine docker

- src/payloads/service.ts
- src/routers/service.ts
- src/routers/services_metadata.ts
- src/utils/variables.ts
This PR add the Sicilia Vola service and the relative CTAs that allow to start the generation and voucher list flows in the app.
> [IASV-13] Add Sicilia Vola service

- src/payloads/service.ts
- src/routers/services_metadata.ts
This PR removes the API to serve service metadata as static content and it adds metadata into the service payload
> Remove services metadata as static content

- assets/html/login.html
- configure.sh
- src/routers/message.ts
Now we can use `globals.autoLogin` in `config/config.json` instead.
> Remove redundant scripts and logic for test login

- src/config.ts
- src/payloads/payload.ts
- src/payloads/wallet.ts
- src/types/config.ts
- src/utils/random.ts
The new config under `wallet.payment` is defined [here](https://github.com/pagopa/io-dev-api-server/compare/IAI-85-payment-config?expand=1#diff-fea291e6a68bacafef88ed99be7ad4916267ab6585b42401f1f76ddcbb37706aR52). 
It will allow us to test the full payment journey with deterministic values.
> Support payment config

- src/payloads/backend.ts
This PR fix a bug introduced with pagopa/io-services-metadata#522 aligning the backendStatus response to the specs in _io-services-metadata_
> [IA-544] Align backendStatus to io-services-metadata

- src/payloads/wallet_v2.ts
- src/routers/wallet.ts
This PR update the `generateWalletV1FromPayPal` payload and the `convertFavouriteWalletfromV2V1` util according to the new [spec.json](https://raw.githubusercontent.com/pagopa/io-app/30acad7ebe51088d97b33f503fffc8673ab0d585/assets/paymentManager/spec.json)
> Fix payment manager wallet type

- src/payloads/message.ts
- src/routers/message.ts
This PR will let the server return an empty string in the HTML body of an MVL. Useful for testing.
> Add MVL without html every 2 messages

- src/routers/message.ts
As per [the latest specs](https://github.com/pagopa/io-backend/pull/864/files#diff-ac5f41902728c87f4277af9405ffbdf02ba3225a7987805c9b9603119e691e7bR323).
Match against `message.id` instead of the `envelope_id` property.
> [IAMVL-69] Use messageId for attachments

- src/payloads/backend.ts
This pr sync the `assistanceTool.tool` with `zendesk` in order to mirror the production response.
> chore: Update backend response with production value

- src/routers/__tests__/wallets.test.ts
- src/routers/walletsV2/index.ts
Update the `/delete-wallets` endpoint adding the `remainingWallets` field in the response.
- adding the `remainingWallets` field in the `/delete-wallets` response.
- update test
Run the tests suite
> [IA-662] Update delete-wallets api

- package.json
- src/payloads/backend.ts
This PR is going to sync the development server with the new Premium Messages configuration from `io-services-metadata` added through https://github.com/pagopa/io-services-metadata/pull/600.
- Upgrade the `io-services-metadata` package used for the specs to `1.0.9`
- Add a `premiumMessages` configuration inside `backend.ts`
👀
> [IA-771] Sync the dev-server with the new Premium Messages configuration

- assets/bonus_available/bonus_available_v2.json
- src/config.ts
- src/payloads/backend.ts
- src/payloads/services/special.ts
- src/types/config.ts
This PR adds the CDC special service and the CDC to the available bonus metadata.
Note that the bonus metadata is filled with fake data and is at the moment not created in production.
> [AP-29] Add cdc service and bonus metadata

- .circleci/config.yml
- package.json
- src/payloads/wallet.ts
- tsconfig.json
This PR is going to fix a type conflict in the Payment Manager caused by https://github.com/pagopa/io-app/pull/3963
- Used the correct specs in `src/payloads/wallet.ts`
- Added a `tsc --noEmit` script in `package.json` and executed it on the CI to add a typecheck
> [IAI-203] Fix the Payment Manager types conflicts

- src/config.ts
This PR is going to sync the default `accepted_tos_version` in the dev server with the one bumped in https://github.com/pagopa/io-app/pull/4048. This will prevent the ToS screen to always appear while using the development environment.
- Bumped `accepted_tos_version` to `4.0`
> Sync the `accepted_tos_version` to `4.0`

- README.MD
This PR adds a missing instruction point to the Setup section in the README file. Such point is the API definition generation, after the `yarn install` command.
- Added the API definitions generation instruction and command on the SETUP section of the README file
Follow the Setup process after repository cloning
> [IAI-249] Update README instructions to include API definitions generation

- assets/contextual_help/data.json
This PR adds the contextual help texts for the push notification opt-in screens.
- Added contextual help texts for "ONBOARDING_NOTIFICATIONS_INFO_SCREEN_CONSENT", "ONBOARDING_NOTIFICATIONS_PREFERENCES" and "PROFILE_PREFERENCES_NOTIFICATIONS" routes (both italian and english)
Run the server instance and check that the contextual help (in the IO application) is correctly populated when opening it from each of the three screens above
> [IOAPPCOM-3] Added contextual help strings for push notification opt-in screens

- package.json
Bump io-services-metadata from 1.0.23 to 1.0.24
- package.json bump to io-services-metadata from 1.0.23 to 1.0.24
Check CI checks for successful completion
> Bump io-services-metadata from 1.0.23 to 1.0.24

- src/routers/public.ts
- src/utils/login.ts
This PR adds the User-Agent validation in the login flow when using LolliPOP and it also adds the HASH algorithm in the `SAMLRequest` query parameter
- `src/routers/public.ts` validates the User-Agent, both syntax and min app version
- `src/utils/login.ts` requires (and adds) the hash algorithm name when computing the `SAMLRequest` string
Make an `HTTP` call to the `/login` endpoint with the 'x-pagopa-lollipop-pub-key' and 'x-pagopa-lollipop-pub-key-hash-algo' headers set.
Without the `User-Agent` header or a malformed one, the response should be an `400 Bad Request`. This also happens if the app version is less than `2.23.0`.
With a proper User-Agent header, like `IO-App/2.23.0`, the request should return a `302 Found` (watch out for automatically followed redirects in your client).
Also …
> LolliPOP login: User-Agent and Hash Algorithm

- src/config.ts
- src/populate-persistence.ts
- src/types/config.ts
- src/utils/variables.ts
This PR adds rejected and signed message type to the dev-server config.
- Update config
- Update message generator
Start dev-server using fci config.json as above:
`{
"profile": {
"attrs": {
"name": "Gian Maria"
}
},
"messages":{
"fci": {
"waitForSignatureCount": 1,
"rejectedCount": 1,
"expiredCount": 1,
"expired90Count": 1,
"waitForQtspCount": 1,
"signedCount": 1
}
}
}`
> chore(Firma con IO): [SFEQS-1523] Add rejected and signed message

- package.json
- src/persistence/lollipop.ts
- src/routers/public.ts
- src/routers/session.ts
Added LP key verification support for login flow
- package.json: updated backend api.
- src/persistence/lollipop.ts: added logic to store `lollipopAssertionRef`.
- src/routers/public.ts: added function to store `lollipopAssertionRef`.
- src/routers/session.ts: added to response payload `lollipopAssertionRef`.
1) Try to send a login payload with a valid `lollipopPublicKeyHeaderValue` and verify if `lollipopAssertionRef` contains the right thumbprint value.
2) Try to `get session` and verify if `lollipopAssertionRef` is in response payload and contains the right value.
> [LLK-66] Added LP key verification support for login flow

- src/routers/services_metadata.ts
This PR responds with a 404 error for the service nr. 4 logo HTTP Request.
This allows us to test the `undefined` image logo scenario for a service.
See changes list.
Run the IO App through the dev server and navigate to national services. The  list should render correctly, while the service nr. 4 should not show a logo.
> [IOAPPFD0-56] Add 404 status on service 4 logo

- src/payloads/features/fci/metadata.ts
- src/populate-persistence.ts
This PR adds a frontmatter for signature request with status SIGNED. Also adds related frontmatter.
- Update frontmatter
- Update populate-persistance
With this config should to generate a message of a signature request with status SIGNED.
`{
"profile": {
"attrs": {
"name": "Gian Maria"
}
},
"messages":{
"fci": {
"signedCount": 1
}
}
}`
> chore(Firma con IO): Add signed message

- config/config.json
- src/persistence/lollipop.ts
- src/routers/features/lollipop/index.ts
- src/routers/public.ts
- src/server.ts
This PR adds the lollipop endpoint `/first-lollipop/sign` to `publicRouter`.
- [src/persistence/lollipop.ts](https://github.com/pagopa/io-dev-api-server/pull/233/files#diff-05cf9f859fe60f756b7fb4ae8f448cab04c77f4706ef05fee53db351fa8a04a5): Adds public key persistence.
- [src/routers/features/lollipop/index.ts](https://github.com/pagopa/io-dev-api-server/pull/233/files#diff-63cd54ee658a7a4b7642857b2a08d3a746aad58d3efe73dfc0507ee29ff83511): Adds specific router.
- [src/routers/public.ts](https://github.com/pagopa/io-dev-api-server/pull/233/files#diff-a8ab3f294071f8e4ff9cdb51c80a7b0410b4c7a0a1b28581b7275339ff65add8): Persists the public key during the login phase.
- [src/server.ts](https://github.com/pagopa/io-dev-api-server/pull/233/files#diff-8a8ae07582c9d433ec8c2e5c4310ff8901e604f4965c5b90 …
> [IOPID-94] Add first lollipop consumer

- src/config.ts
- src/payloads/features/fci/signature-request.ts
- src/populate-persistence.ts
- src/routers/features/fci/index.ts
- src/types/config.ts
- src/utils/variables.ts
This PR adds signature request with no fields.
- Update payloads
- Update config
- Update getSignatureRequestById
Tests should solve correctly. Using a config to generate a signature request with no fields a message should appear in io-app. The signing flow shouldn't have signature fields.
> chore(Firma con IO): [SFEQS-1651] Add signature request with no fields

- src/routers/features/lollipop/index.ts
This PR return an error when the `signature-input` header is empty.
See commit list
Try the lollipop playground with IO-APP by providing an empty string for `signature-input` header.
Using Proxyman you can do that by scripting over this url: http: //localhost:3000/first-lollipop/sign
```js
async function onRequest(context, url, request) {
// console.log(request);
console.log(url);
// Update or Add new headers
//delete request.headers.signature;
//delete request.headers["signature-input"];
request.headers["signature-input"] = ""
//request.headers["signature"] = ""
//request.headers["content-digest"] = "foo"
// Done
return request;
}
```
> chore: Fix no error on empty "signature-input" header

- README.MD
- src/config.ts
- src/middleware/lollipopMiddleware.ts
- src/routers/__tests__/message.test.ts
- src/routers/features/lollipop/index.ts
- src/routers/message.ts
- src/types/config.ts
This PR refactors lollipop checks and adds the new lollipop middleware.
- Lollipop logic in `src/routers/features/lollipop/index.ts` has been moved to `src/middleware/lollipopMiddleware.ts`
- The following endpoints use the lollipop middleware:
- message precondition
- third party message
- third party message attachments
- lollipop playground
- global configuration to disable every lollipop middleware in `/src/config.ts`
- README.md updated with instructions on how to use lollipop
- With the global lollipop configuration enabled, check that the previous endpoints do not work with improper headers.
- Repeat the same test but with global lollipop configuration disabled (endpoints shall work)
- Using the latest master deploy of io-app (with lollipop enabled globally), check that, for any PN …
> [IOCOM-253,IOCOM-258] Lollipop middleware and third party message endpoints with lollipop

- src/payloads/backend.ts
This PR changes the lollipop min app version to 0.0.0 in order for the it-wallet POC to work with the dev server. 
The POC starts from version 0.0.0. 
- `src/payloads/backend.ts`: Changes the lollipop min app version to 0.0.0.
Run the io-dev-api-server and the app pointing at the `bundle/it-wallet` branch.
Comment the following code in `ts/screens/modal/RootModal.tsx`: 
`if (!props.isAppSupported) {
void mixpanelTrack("UPDATE_APP_MODAL", {
minVersioniOS: props.versionInfo?.min_app_version.ios,
minVersionAndroid: props.versionInfo?.min_app_version.android
});
return <UpdateAppModal />;
}`
Login should be successful.
> [SIW-240] Set lollipop min app version to 0.0.0

- package.json
- src/payloads/features/cgn/merchants.ts
- src/payloads/features/cgn/utils.ts
This PR adds new mock for new mandatory attributes of `Merchant`: `supportType`, `supportValue` and `allNationalAddresses` in order to show a new "Contact section" into merchant details screen.
- Added an `util.ts` file under `cgn` folder with all the utilities used for that feature;
- Mapped all three mandatory attributes for the mocked response;
Use postman in order to check if the response of _GET /merchants/:merchantId_ gives as output `supportType`, `supportValue` and `allNationalAddresses`
> chore: [PE-453,PE-454] Add support type, value and allNationalAddresses flag to merchant

- src/payloads/features/idpay/get-initiatives-with-instrument.ts
This PR fixes the `/wallet/instrument/{walletId}/initiatives` endpoint, which returns the initiatives status for a payment method.
- `getInitiativeWithInstrumentResponse` now returns the status of all initiatives and not only for the active initiatives
-  `getWalletById` now has an `enabledFunctions` filters to exclude wallets without BPD capabilities
> Fix: IDPay initiatives status by wallet id

- src/features/pn/payloads/messages.ts
- src/features/pn/types/notificationRecipient.ts
This PR adds the `recipientType` in the `NotificationRecipient` payload.
- updated type
- updated payload
using postman check that the response contains the `recipientType` property
> [IO-558] Add recipientType in the NotificationRecipient payload

- src/payloads/message.ts
- src/routers/payment.ts
This PR adds successful payment tracking and storing in the in-memory payments' database.
- Payments generation on messages stores the processable payment into the payments' database
- Payments processing updates a successful payment in the payments' database (through the payments' routing)
Try to pay a message's payment and check that the process succeeds. Upon completion, try to pay the same payment again. An "already-paid" error should be reported
> [IOCOM-563] Payment completion tracking through payments' database

- assets/html/login.html
This PR adds the 1002 login error.
> [IOPID-966] Add 1002 login error

- src/persistence/idpay.ts
- src/routers/features/idpay/barcode.ts
- src/routers/features/idpay/index.ts
added handling for idpay barcode generation and expire mechanics
- added handler for idpay barcode
- added handler for said barcode expiration
run a bunch of postman queries for `payment/bar-code` with `{"initiativeId": "..."}` as body
> [IOBP-347] addition of IDPAY barcode

- src/config.ts
- src/features/messages/persistence/messagesPayload.ts
- src/features/messages/services/messagesService.ts
- src/features/messages/types/messageTemplate.ts
- src/features/messages/types/messageTemplateWrapper.ts
- src/features/messages/types/messagesConfig.ts
- src/populate-persistence.ts
- src/routers/__tests__/message.test.ts
This PR allows to generate messages with remote content.
- `src/config`: added configuration for messages with remote content
- `src/populate-persistence.ts`: added generation of messages with remote content (saved in-memory)
- `src/features/messages/persistence/messagesPayload.ts`: added `withRemoteContent` function that adds remote content to the message
Run the server instance with different configurations and check that the payload returned by the `/messages/:id` and `/third-party-messages/:id` endpoints is correct
> [IOCOM-686] Add message generation with remote content

- src/types/config.ts
This PR makes email user field as optional.
> chore: set user email as not mandatory

- src/features/wallet/routers/payment.ts
- src/features/wallet/types/configuration.ts
- src/features/wallet/types/failure.ts
- src/types/config.ts
This PR adds the ability to force a failure during the payment verification and activation request.
- To simulate a failure during the verification request, add the following configuration in your config.json :
```json
"features": {
"wallet": {
"verificationFailure": {
"faultCodeCategory": "PAYMENT_UNAVAILABLE",
"faultCodeDetail":"PPT_PSP_SCONOSCIUTO"
}
}
}
```
Check that the `GET /payment-requests/:rpt_id` endpoint returns a failure
-  To simulate a failure during the activation request, add the following configuration in your config.json :
```json
"features": {
"wallet": {
"activationFailure": {
"faultCodeCategory": "PAYMENT_UNAVAILABLE",
"faultCodeDetail":"PPT_PSP_SCONOSCIUTO"
}
}
}
```
Check that the `POST /transaction` endpoint returns a failure
> [IOBP-309,IOBP-312] Add ability to generate failure for payment verification and activation requests

- src/features/wallet/routers/payment.ts
This PR adds `GET /wallets` and `GET /payment-methods` endpoint for payment flow
> [IOBP-529] Add eCommerce payment methods endpoints

- assets/html/homeDashboard.html
- assets/html/messages.html
- src/config.ts
- src/features/messages/persistence/messagesDatabase.ts
- src/features/messages/routers/messagesRouter.ts
- src/features/messages/services/messagesService.ts
This PR adds a new endpoint to create a new message while the dev-server is running.
- message creation in `MessagesService`
- message in-memory storage in `MessagesDatabase`
- message creation endpoint in `MessagesRouter`
Call the `POST message` endpoint and check that the message is correctly created and retrieved using the `messages` endpoint
> [IOCOM-1091] Add a message endpoint to create a new message

- src/features/wallet/persistence/userWallet.ts
This PR adds an expired payment method in the wallet payload
> chore: add expired card in wallet

- README.MD
- assets/spid/idps/list.json
Update IDPs list with metadata list2 and modify readme.md adding uniqueness email validation informations
> [IOPID-1502] update IDPs list and readme.md

- src/config.ts
- src/features/services/payloads/get-featured-items.ts
- src/features/services/routers/featured.ts
- src/features/services/routers/index.ts
- src/features/services/types/configuration.ts
- src/persistence/services.ts
Added new `/featured` api mock implementation that returns a list of highlighted _services_ and/or _institutions_.
_**FeaturedItems Api**_ returns a list with max 5 items _(this size is configurable through the `ioDevServerConfig.features.service.featuredItemsSize` parameter)_. 
- Follow commit for details
Check api locally by calling `http://192.168.1.172:3000/api/v2/featured`.
> [IOPAE-1117] Add services `/featured` api mock

- src/routers/__tests__/server.test.ts
- src/routers/public.ts
>[!Warning]
> This PR is related to this PR the io-app: https://github.com/pagopa/io-app/pull/5996
> The demo of how it works is in the PR in io-app
In this PR, token generation logic was added to the test login
- Start the app using .env.local environment;
- Press the button “Login with SPID”;
- make your choice at the opt-in screen
- Here the trick to activate test form: 5 taps inside the the banner explaining how much time you have to authenticate (see attached video for how to);
- A login form should be loaded;
- Fill the form with the provided credentials (it is case sensitive);
- Press confirm button.
I the login is successful and the app flow starts, then the PR works!
> [IOPID-92] Add logic to use lollipop in test login

- package.json
- src/payloads/features/idpay/get-timeline-detail.ts
- src/persistence/idpay.ts
- src/routers/features/idpay/payment.ts
This PR adapts the IDPay definitions API mock with the new openAPI
- Updated the IDPay openAPI;
- Converted every value from precision number to cents;
> chore: [IOBP-909] Adapt IDPay definitions mock API

- package.json
- src/features/payments/persistence/notices.ts
- src/features/payments/persistence/transactions.ts
- src/features/payments/routers/index.ts
- src/features/payments/routers/notices.ts
- src/features/payments/routers/payment.ts
- src/features/payments/routers/router.ts
- src/features/payments/routers/transactions.ts
- src/features/payments/utils/transactions.ts
This PR adapts the new openAPI provided by biz events;
- Adapted the new open API of biz-events replacing from "transaction" to "notice";
Test this PR with the following io-app PR: https://github.com/pagopa/io-app/pull/6187 in dev-env.
> chore: [IOBP-927] Adapt new openAPI biz-events

- src/config.ts
- src/features/payments/routers/notices.ts
- src/types/config.ts
Include a summary of the changes.
This pull request includes changes to the payment route to support a new endpoint for disabling user notices.
- Add `paids/:eventId/disable` route
- Update global config with `hideReceiptResponseCode` field
> feat: [IOBP-838] Remove receipt from list endpoint

- CODEOWNERS
This PR adds our collaborators from other companies as CODEOWNERS in order to allow them to approve the PR
> Add collaborators as codeowners

- assets/wallet/wallet_payment.html
This PR adds outcome 99 inside the mocked payment webpage 
- Added outcome 99 as `BE_NODE_KO` inside the dropdown that shows when starting the payment flow in-app
Describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
> chore: [IOBP-982] Add outcome 99 into mock webview payment page

- assets/wallet/wallet_payment.html
This PR adds the `PSP_ERROR` outcome inside the payment flow webpage
- Added the PSP_ERROR inside the dropdown shown in the payment flow webpage.
> chore: [IOBP-981] Add `PSP_ERROR` outcome into payment flow webpage

- assets/contextual_help/data.json
This PR add missing German translation(`de`) in `contextual_help` data, as defined in the [io-services-metadata repo](https://github.com/pagopa/io-services-metadata)
> feat: [IOBP-961] German translation as defined in service metadata

- src/features/fims/services/relyingPartyService.ts
This PR adds the "Close" button the the example authenticated Relying Party's web page.
- link (and button) that closes the InApp Browser using the `iossoapi` protocol
Using the related IO App branch, check that the In App browser is closed correctly.
> [IOCOM-2009] FIMS RP page close link

- assets/assistanceTools/zendesk.json
- package.json
The local version (on the dev-server) did not comply with what was imposed by the specifications in app io, which is why the decoder would fail and not allow the service stream to be opened.
The version to which the specifications point has been updated and the zendesk file that contains the data made mandatory has been updated
| before alignment | after alignment |
| - | - |
| <video src="https://github.com/user-attachments/assets/052ca9e9-78bc-40af-98f9-cf633e25a2f1"/> | <video src="https://github.com/user-attachments/assets/21f310de-053e-40fe-834b-0eb2065cba36"/> | 
Run the application as you can see from the video demo
> Align content-specs to latest version of io-services-metadata

- src/features/payments/payloads/transactions.ts
This PR adds a mocked field `onUs` inside of the available PSP list.
- Added `onUs` field to one of the PSP inside the list.
> chore: [IOBP-1140] Add onUs mocked field on PSP list

- package.json
This pull request includes a minor update to the `package.json` file. The change updates the URL for the `api_cgn_merchants` specification to point to a new release version (`v16.7.4-RELEASE` instead of `v16.7.3-RELEASE`)
> chore: [PE-786] CGN update api version

- src/routers/features/idpay/__tests__/payment.test.ts
This PR fixes an IDPay test that fails randomly.
- Added the `8` character in the `trxCode` of the `PUT putAuthPayment` test.
Tests should pass without any problem.
> fix: [IOBP-1167] Random IDPay test fails

- src/persistence/idpay.ts
This PR mocks the `webviewUrl` attribute with a mocked FIMS URL inside the IDPay expense initiative.
- Added a mock to a URL with FIMS when creating the mocked initiative bonus.
> chore: [IOBP-1137] Mock webviewUrl with FIMS url into IDPay expense initiative

- scripts/generate-api-models.sh
- src/payloads/backend.ts
- src/payloads/session.ts
>[!Important]
> Depends on [this PR](https://github.com/pagopa/io-services-metadata/pull/937)
This PR upgrades the `IO_SERVICES_METADATA_VERSION` and the `IO_SESSION_MANAGER_VERSION`, it adds the `loginConfig` field in the `src/payloads/backend.ts` file and the `expirationDate` field in the `PublicSession` object in order to allow tests in [this PR](https://github.com/pagopa/io-app/pull/6736)
- Upgraded `IO_SERVICES_METADATA_VERSION`
- Upgraded `IO_SESSION_MANAGER_VERSION`
- Added `loginConfig` field in the `src/payloads/backend.ts` file
- Added the `expirationDate` field in the `PublicSession` object
Follow the instruction in [this PR](https://github.com/pagopa/io-app/pull/6736)
> [IOPID-2719] FastLogin expiration date

- src/payloads/backend.ts
addition of said banner's ID to the payloads object
- addition of banner ID
when checking out this PR: https://github.com/pagopa/io-app/pull/6756
after enabling the banner in app, it should correctly render in the second place.
> [IOCOM-2086] addition of SEND banner to payload

- scripts/generate-api-models.sh
- src/config.ts
- src/features/fims/routers/relyingPartyRouter.ts
- src/features/fims/services/historyService.ts
- src/features/messages/persistence/messagesPayload.ts
- src/features/messages/services/messagesService.ts
- src/features/payments/payloads/payments.ts
- src/features/pn/payloads/messages.ts
- src/features/pn/services/services.ts
- src/features/services/payloads/get-featured-services.ts
- src/features/services/payloads/get-institutions.ts
- src/features/services/payloads/get-services.ts
- src/features/services/persistence/services/factory.ts
- src/features/services/persistence/services/special/cdc-service.ts
- src/features/services/persistence/services/special/cgn-service.ts
- src/features/services/persistence/services/special/fci-service.ts
- src/features/services/persistence/servicesDatabase.ts
- src/features/services/routers/institutions.ts
- src/features/services/routers/services.ts
- src/features/services/types/configuration.ts
- src/features/services/utils/institutions.ts
- src/payloads/features/idpay/get-initiative-beneficiary-detail.ts
- src/payloads/payload.ts
- src/routers/__tests__/service.test.ts
- src/routers/features/idpay/__tests__/wallet.test.ts
- src/routers/payment.ts
- src/routers/service.ts
- src/routers/services_metadata.ts
- src/types/config.ts
- src/utils/payment.ts
This PR depends on https://github.com/pagopa/io-backend/pull/1205 and https://github.com/pagopa/io-dev-api-server/pull/476
This PR introduces the new GET `getServiceById` to retrieve service details, while removing the old endpoint.
You can test this PR using a REST client
> [IOPAE-1916] Add get serviceById v2

- scripts/generate-api-models.sh
- src/payloads/backend.ts
This PR adds the `webViewPaymentFlow` remote feature flag to mock the enabled version.
- Changed the `IO_SERVICES_METADATA_VERSION` value so that ASAP the dependent PR will be merged, must be updated with the correct version;
> chore: [IOBP-1577] add `webViewPaymentFlow` feature flag

- scripts/generate-api-models.sh
- src/payloads/backend.ts
This PR introduces updates to the API model generation and backend configuration payloads to support new FIMS service configurations and CdC onboarding remote url.
* [`src/payloads/backend.ts`](diffhunk://#diff-7ff7240bd72d8e1a05d545469bd2840db7ce9a138c2172e29389c43a39f9a0c1R69-R73): Added a new service configuration for "Carta della Cultura - Onboarding" with its associated `configuration_id`, `service_id`, and `service_name`.
* [`src/payloads/backend.ts`](diffhunk://#diff-7ff7240bd72d8e1a05d545469bd2840db7ce9a138c2172e29389c43a39f9a0c1R87-R89): Introduced a new `cta_onboarding_config` object with a URL for the CDC onboarding API endpoint.
> chore: [IOBP-1727] Add CdC FIMS mock config

- src/persistence/payments.ts
This PR fixes the dueDate format conversion.
- dueDate was being stored as a Date into paymentData but its type was a PatternString(YYYY-MM-DD)
> fix: [IOCOM-2302] Fix bad conversion for dueDate in paymentData

- src/features/services/persistence/servicesDatabase.ts
This pull request updates the `createServices` function to include IDPay services in the calculation of `specialServices`. 
- Modified the calculation for `specialServices` by adding the length of `generateIDPayServices()` to include IDPay services in the count.
Ensure that everything works as expected
> chore: [IOAPPX-000] Add IDPay service count to `specialServices`

- src/features/messages/services/ioSendService.ts
- src/features/pn/services/aarService.ts
This PR fixes the `x-pagopa-pn-io-src` header and a bad response code for the QRCode API.
- `x-pagopa-pn-io-src` header's value was not being transferred from client to SEND router
- 403 is returned when an AAR QRCode not belonging to the user is requested
Request a notification (IO Endpoint) without the `x-pagopa-pn-io-src` header set: a warning should appear in the console. Check it again with the value of such header set to "QRCODE": no warning should appear
Check the AAR endpoint (IO Endpoint) with a QRCode content that does not belong to the user: it should return 403.
> fix: [IOCOM-2585] Fix for `x-pagopa-pn-io-src` header and 403 on AAR QRCode not belonging to user

- src/payloads/features/idpay/check-prerequisites.ts
- src/payloads/features/idpay/get-initiative-data.ts
- src/payloads/features/idpay/get-onboarding-initiative-user-status.ts
- src/payloads/features/idpay/types.ts
- src/persistence/idpay.ts
- src/routers/features/idpay/onboarding.ts
This PR introduces enhancements to the IDPay onboarding and initiative management features. The improvements include the ability to track and retrieve user-initiated onboardings that are on the waiting list.
* Added a new in-memory store (`onboardedInitiativeStatuses`) to track the onboarding status of users for initiatives, along with a function `addOnboardedInitiativeStatus` to update this store.
* Introduced the `getOnboardingInitiativeUserStatus` function to retrieve all initiatives for which the user is in the waiting list or evaluation status, and exposed a new GET endpoint `/onboarding/user/initiative/status` to return this data.
* Updated the onboarding PUT handler to add the user to the waiting list when prerequisites are met, using the new tracking mechanism.
- Start an …
> feat: [IOBP-1985] Add user onboarded initiative list statuses API
