- src/payloads/message.ts
- src/server.ts
- src/utils/id.ts
This PR adds a better generation of messages with content
- each message id (from /messages) has its own message with content
- in getMessageWithContent you specify as optional parameters:
- due date
- amount
> Improve message with content

- .circleci/config.yml
- src/server.ts
This PR setups the CI with [circleCI](https://circleci.com/)
> Add CircleCI

- src/__tests__/service.test.ts
- src/payloads/message.ts
- src/payloads/service.ts
- src/server.ts
This PR adds services by scope API
This is about static content (see https://github.com/teamdigitale/io-services-metadata/pull/73)
> Add services by scope

- src/__tests__/installation.test.ts
- src/__tests__/profile.test.ts
- src/__tests__/service.test.ts
- src/payloads/municipality.ts
- src/payloads/response.ts
- src/payloads/success.ts
- src/server.ts
This PR adds:
- installations (**put** to save the notification token)
- municipality (**get** to retrieve the metadata about a municipality)
> Add installations and municipality paths

- README.MD
Updated README.md with instructions to run docker container
> [#171602183]-add docker guidelines

- src/__tests__/emailValidationProcess.test.ts
- src/server.ts
It allows devs to see the ui feedback when the user request is submitted to backend
> add response to email-validation-process

- src/__tests__/info.test.ts
- src/payloads/backend.ts
- src/server.ts
This PR adds the support to the backend status info
see https://iopstcdnassets.z6.web.core.windows.net/status/backend.json
> Support backend status

- package.json
- src/__tests__/transactions.test.ts
- src/payloads/wallet.ts
- src/server.ts
- yarn.lock
This PR introduces a support for transactions list pagination
> supporting transactions list paginations

- .gitignore
- src/payloads/message.ts
- src/server.ts
- src/utils/strings.ts
- src/utils/variables.ts
Message builder functions:
- less code
- better naming
- more flexibility
> Code refactoring

- src/payloads/error.ts
- src/routers/__tests__/userDataProcessing.test.ts
- src/routers/profile.ts
This PR add the API that allow a user to request the abort of the profile delete
> [#175434754] Abort delete userdataprocessing API

- src/global.ts
- src/payloads/payload.ts
- src/payloads/wallet.ts
- src/payloads/wallet_v2.ts
- src/routers/__tests__/wallets.test.ts
- src/routers/payment.ts
- src/routers/wallet.ts
- src/routers/wallet_v2.ts
- src/utils/file.ts
- add VERIFICA, ATTIVA, CHECK payment API
- add set favourite wallet API
- restore random brand picking when a credit card is generated
- improve tests
> Support payment flow

- src/payloads/backend.ts
- src/payloads/types/backendStatus.ts
This PR add the section status needed to report any temporary disruption in the cobadge screen
> [#176575663] Add cobadge section

- src/routers/features/cgn/index.ts
This PR fixes the API Specifications for CGN after the renaming of some types and attributes
> [#176963464] Update cgn types definitions

- src/payloads/response.ts
- src/routers/__tests__/server.test.ts
- src/routers/__tests__/wallets.test.ts
- src/routers/features/cgn/index.ts
Hi! As per subject I fixed the error that blocked the tests and added some tests to complete public.ts at 100%
> Fixed some errors and added some test

- package.json
- src/payloads/response.ts
- src/routers/__tests__/server.test.ts
- src/routers/__tests__/wallets.test.ts
- src/routers/features/bdp/__tests__/index.test.ts
- src/routers/features/bdp/index.ts
- src/routers/features/cgn/index.ts
- src/routers/public.ts
- src/routers/services_metadata.ts
This PR manages the integration of the `/bpd/io/citizen/v2` API.
- Added citizen V2 swagger to allow type generation
- Added GET `/io/citizen/v2` API
- Added PUT `/io/citizen/v2` API
> [#177542335] Citizen v2 api integration

- src/payloads/backend.ts
This PR add the new `favourite_language` section to the `backendStatus` payload
> [IA-97] Add favourite_language section

- package.json
> [IA-412] Change PaymentManager API spec end-point

- package.json
- src/config.ts
- src/payloads/wallet_v2.ts
- src/routers/wallet.ts
- src/routers/walletsV2/index.ts
- src/types/PatchedWalletV2.ts
- src/types/config.ts
This PR adds paypal as payment method
- set how many paypal accounts are included in to the wallet
- set how may paypal account the user holds (that can be search with the app)
> [IA-446] Add paypal as payment method

- assets/pm/paypal/psp_account.json
- package.json
- src/payloads/wallet.ts
- src/payloads/wallet_v2.ts
- src/routers/__tests__/paypal.test.ts
- src/routers/walletsV3/methods/paypal.ts
This PR sync the spec and API with the last changes of the PM
> [IA-504] Sync Paypal spec

- src/payloads/backend.ts
This PR modify the zendesk ff value in the `backend` payload according to https://github.com/pagopa/io-services-metadata/pull/525
> [IA-549] Modify zendesk ff value

- assets/pm/psp/pspV2.json
- package.json
- src/routers/__tests__/wallets.test.ts
- src/routers/walletsV2/index.ts
> [IA-525] Add psp list API - V2

- CODEOWNERS
- src/config.ts
- src/payloads/backend.ts
- src/routers/payment.ts
- src/routers/wallet.ts
- src/types/config.ts
- src/utils/payment.ts
This PR makes these sections configurable
- assistance tool (zendesk, instabug, web...)
- payment outcome (!= 0 -> payment error)
🐞  
- a credit card is added even if the outcome code is a failure
> [IA-568,IA-477,IA-476] Update config

- src/routers/features/cgn/merchants.ts
This PR integrates and properly handles the DiscountCodeType attribute on a OnlineMerchant for CGN discount app visualization
> [IOACGN-5] Integrates discount code type on online merchants

- package.json
- src/config.ts
- src/payloads/backend.ts
- src/routers/walletsV2/index.ts
- src/types/config.ts
This PR handles the remote config for paypal
> [IA-614] Handle paypal remote config

- assets/html/services_web_view.html
- src/routers/service.ts
This PR improves the visualization of local service web page (embedded in IO app)
| before  | now |
| ------------- | ------------- |
> [IA-428] Display local services with organization and service names

- package.json
- src/payloads/backend.ts
This PR supports the new remote CGN Config
> [IOACGN-20] Support CGN remote config

- src/payloads/services/index.ts
- src/payloads/services/special.ts
- src/routers/features/cgn/index.ts
- src/routers/service.ts
This PR aims to properly handle the special services activation status. 
CGN activation now effects the related service activation
> Implements handler for special services activation

- package.json
- src/routers/features/cgn/merchants.ts
This PR implements the `getDiscountBucketCode` for CGN merchants discounts.
> [IOACGN-12] Implements discount-bucket-code API

- package.json
- src/payloads/backend.ts
This PR aligns the content specs definitions and the values with the production.
> Update content-specs definitions

- assets/status/versionInfo.json
This pr syncs `status/versionInfo.json` with the production values
- Update `status/versionInfo.json`
> chore: Sync versionInfo with production values

- package.json
- src/payloads/backend.ts
This PR aligns the backend config with the production adding the donation config.
> [IA-697] update backend config with donation

- src/payloads/backend.ts
This PR updates the donate url to address the last developments
> Update donate url

- assets/html/donate.html
This PR is going to add various fixes to the donations HTML page.
https://user-images.githubusercontent.com/5963683/157679239-8ec78d36-f9b7-406a-ae22-b6f6476b78d2.mov
https://user-images.githubusercontent.com/5963683/157686103-e7b9abdf-bb0c-426e-8d25-7086489ae7d0.mov
- Fixed `più` copy typo
- The radio button is now a simple HTML element styled, and should not appear as a native element anymore. This was fixed using the `input + label` method.
- The footer is now fixed to the bottom of the page
- Disabled the copy interaction inside the page
- Removed the trailing zeroes for all the currencies
- Added a space between the radio button and the text
- Replaced the native function `replaceChildren` with a custom one since it's not well supported everywhere
Run the dev server and navigate to …
> [IA-718] Fix donations page issues

- assets/html/donate.html
This PR is going to improve the accessibility in the donations page.
**N.B.** There are hard-coded values like `Pulsante di scelta` because using the native elements inside the web-view would cause various words to not be translated in Italian.
https://user-images.githubusercontent.com/5963683/158809171-64a941d8-8511-43a2-ae49-46837d9ebd8c.mov
- Removed the `input + label` hack in favour of pure JavaScript, since it would cause accessibility issues
- Added more `aria` attributes
- Added a custom label to the charity radio button and the donation amounts
- Added automatic focus on various elements in order to have a better navigation flow
Run the donation page using the device's Voice Over, the experience should match the one described in the ticket.
> [IA-722] Improved donations page accessibility

- assets/html/donate.html
This PR sync donation.html with the official one published in CDN
> UADonation: sync donation.html with last changes done in CDN

- assets/status/versionInfo.json
This pr sync the `versionInfo.json` with the production.
> Sync `versionInfo.json` with the remote data

- src/payloads/backend.ts
This PR enables donation banner to mirror the production
> Enable donation banner to mirror the production

- src/routers/message.ts
As per https://github.com/pagopa/io-app/pull/3863
> [IA-773] Rename query parameter 

- assets/data/availableDonations.json
- src/routers/public.ts
This PR makes some refactoring to move a large payload from code to a dedicated json file
> Move donation payload in a dedicate json file

- src/routers/profile.ts
If the `profile` section allows random value, dev server fills profile name and surname with random value
This could be useful to propose different profile attributes to the app instead of a fixes one
> Profile name, surname and email could be random

- src/config.ts
- src/routers/features/cgn/index.ts
- src/types/config.ts
This PR aims to improve the dev-server configuration in order to make editable the eligibitlity to EYCA or CGN cards
> Improves the configuration of dev-server to define if the user is eligible or not to a CGN or Eyca cards

- src/routers/features/cdc/__tests__/bonusRequest.ts
- src/routers/features/cdc/bonusRequest.ts
This PR updates the API path by adding the `cdc` prefix
> [AP-27] Update cdc API path

- assets/bonus_available/bonus_available_v2.json
This PR updates the CDC bonus data as proposed by design.
Note that the English version is not yet provided so is unfilled.
> chore: Update cdc bonus data

- .circleci/config.yml
- package.json
This PR to fix the generator script introduced here https://github.com/pagopa/io-dev-api-server/commit/7d7bb28ad920e44881c95e3008a668468926f781
- Update `package.json`
- Update `config.yml`
run `yarn generate`
> Fix generate command

- README.MD
This PR updates generator instruction in readme file
- Edited `yarn generate:all` to `yarn generate`
- Check repository initial page for visual confirmation
- Clone project, follow setup instruction and check server can be run succesfully
> [IOAPPFD0-20] Update instructions in readme file

- package.json
- src/payloads/backend.ts
This PR adds a lollipop feature flag to enable/disable the lollipop feature
> [IOAPPCIT-25] Add feature flag for LolliPOP

- package.json
- src/payloads/backend.ts
This PR adds `min_app_version` field to `lollipop` flag.
> [IOAPPCIT-38] Add min_app_version to lollipop flag

- src/populate-persistence.ts
This PR fixes the persistence of messages with remote attachments according with the server configuration.
- src/populate-persistence.ts: add missing check.
Run io-app against the dev server configuring 0 messages with remote attachments and see that no message of this kind is present. Add some messages with remote attachments in configuration and check that those messages will be shown.
> [IOAPPFD0-30] - Add missing check to the persistence of messages with remote attachments

- src/config.ts
This PR synchronizes the minimum TOS version to https://github.com/pagopa/io-app/pull/4388.
That makes e2e tests work again.
> [LLK-34] Bump min TOS version from 4.1 to 4.4

- package.json
This PR update FCI definitions.
- Update package.json
Describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
> chore(Firma con IO): [SFEQS-1510] Update fci specs

- assets/html/login.html
This PR fixes the regression on the login failure simulator.
- assets/html/login.html: fixed the link to call when the error button is pressed.
Try to login with Dev Server and simulate an error.
> [IOAPPFD0-65] Regression on login failure simulator

- src/config.ts
This PR bumps TOS version from 4.4 to 4.5
> [IA-906] Bump TOS version from 4.4 to 4.5

- package.json
- src/payloads/features/idpay/onboarding/data.ts
- src/payloads/features/idpay/timeline/data.ts
- src/payloads/features/idpay/wallet/data.ts
This PR updates the IDPay API specs and introduces new PDND enums for the onboarding
> [IODPAY-216,IODPAY-221] Update IDPay API specs for onboarding PDND criteria

- src/persistence/lollipop.ts
- src/routers/profile.ts
- src/routers/public.ts
- src/utils/__tests__/httpSignature/ec.test.ts
- src/utils/__tests__/httpSignature/rsa.test.ts
- src/utils/httpSignature.ts
This PR fixes ESLint errors and warnings issues on the Citizen and Auth stream.
See commit and changed files list.
> [IOPID] Fix ESLint errors and warnings

- src/payloads/services/factory.ts
- src/persistence/messages.ts
- src/populate-persistence.ts
- src/routers/message.ts
This PR fixes eslint errors and warnings on behalf of IOCOM team.
> [IOCOM-282] Fixing eslint errors and warnings

- README.MD
- src/config.ts
- src/persistence/sessionInfo.ts
Updated Readme and config for FL
- README.MD: added section for FL.
- src/config.ts: added default value for session TTL.
- src/persistence/sessionInfo.ts: added an error in console to be more explicit in case it occurs.
Enable fast login FF without manually configure a TTL and try to run IO app with a brach that includes FL feature.
> [IOPID-355] Updated Readme and config for FL

- src/payloads/wallet_v2.ts
- src/persistence/appInfo.ts
- src/persistence/lollipop.ts
- src/persistence/sessionInfo.ts
- src/routers/__tests__/wallets.test.ts
- src/routers/features/fci/index.ts
- src/routers/wallet.ts
- src/routers/walletsV2/index.ts
- src/routers/walletsV2/methods/bancomat.ts
- src/routers/walletsV2/methods/cobadge.ts
- src/utils/date.ts
- src/utils/file.ts
- src/utils/strings.ts
This PR fixes some lint warnings/error as described in [this](https://pagopa.atlassian.net/wiki/spaces/IOAPP/pages/716998978/IO-Dev-Api-Server+ESLint) document. Some of them are actually related to the existing wallet section. That's mostly legacy code which we decided to keep this way at the moment, thus warnings and errors have been suppressed.
Please @mastro993 and @forrest57 check them out, thank you.
There are also a few warnings related to the login process. 
Please @SabPicariello check them out, thank you.
- `src/routers/features/fci/index.ts`: Replaces the nested ternary operators with a switch case;
- Everything else is basically just suppressed warnings/errors/
- Run `yarn lint` with strict rules and warnings/errors should be gone for good
> [SFEQS-1773] Fix linting

- assets/html/myportal_playground.html
This PR updates `myportal_playground`.
- added `setTitle`: sets the title of the screen
- added `showToast`: shows a toast
Change the `withCTA` configuration to generate a message with FIMS CTA and enable the [FIMS dev feature flag](https://github.com/pagopa/io-dev-api-server/blob/e3ac6784acecbb5ad80a44dfc7777f80946dcab5/src/payloads/backend.ts#L45) in `src/payloads/backend.ts`.
Using the `io-app`, open a FIMS message and tap the FIMS CTA at the bottom.
Set title from the playground.
> [IOCOM-346,IOCOM-347] Added setTitle and showToast on playground

- package.json
This PR fixes the IDPay specification url in `package.json`
- Added v2.114.1 tag in IDPay specifications url
> Fix: IDPay API specifications in `package.json`

- src/payloads/features/idpay/onboarding-status.ts
- src/routers/features/idpay/__tests__/onboarding.test.ts
- src/routers/features/idpay/onboarding.ts
This PR fixes a bug in the onboarding status endpoint
> [IOBP] Fix IDPay onboarding status endpoint

- src/payloads/features/idpay/onboarding-status.ts
- src/routers/features/idpay/__tests__/onboarding.test.ts
- src/routers/features/idpay/__tests__/wallet.test.ts
- src/routers/features/idpay/wallet.ts
This PR fixes the unsubscription for random generated initiatives or initiatives with random `ulid` as id.
Tests should solve correctly.
> [IOBP] Fix IDPay unsubscription for random initiatives

- src/middleware/fastLoginMiddleware.ts
This PR returns the right 401 response type for IDPAY.
> chore: Add 401 return type for IDPAY

- src/config.ts
- src/routers/__tests__/message.test.ts
This PR disables the active PN configuration
- config: changed in order to not generate any PN message or service by default
Run the server instance and check that there are no PN messages no services
> [chore] PN configuration disabled by default

- package.json
- src/persistence/idpay.ts
- src/routers/features/idpay/__tests__/payment.test.ts
- src/routers/features/idpay/payment.ts
updated idpay api definitions for error cases
- package.json
- updated occurrences where needed
`yarn jest`, also try running the app with the branch https://github.com/pagopa/io-app/tree/IOBP-380-new-idpay-error-handling-dtos
> [IOBP-385] updated idpay api definitions 

- assets/wallet/wallet_onboarding.html
This PR adds the missing outcomes from the wallet onboarding webview page
- Added into dropdown the other available onboarding outcomes value
> chore: [IOBP-375] Add other error outcomes into new wallet onboarding webpage

- package.json
- src/persistence/idpay.ts
- src/routers/features/idpay/barcode.ts
updated IdPay barcode definitions and handler
see short description
with https://github.com/pagopa/io-app/pull/5278, make sure the barcode correctly renders.
also `yarn jest`
> [IOBP-424] update IdPay barcode definitions and handler

- src/config.ts
This PR updates the accepted ToS version to 4.7
- Update config.ts with new ToS version 4.7
> [IOCOM-740] Update config.ts with new ToS version

- src/config.ts
This PR bumps ToS version from `4.7` a `4.8`
> [IOPID-1301] - Bump ToS version from 4.7 a 4.8

- src/config.ts
Reverts pagopa/io-dev-api-server#336
> Revert "[IOPID-1301] - Bump ToS version from 4.7 a 4.8"

- src/config.ts
Reverts pagopa/io-dev-api-server#337
> Revert "Revert "[IOPID-1301] - Bump ToS version from 4.7 a 4.8""

- src/features/wallet/routers/payment.ts
This PR adds `POST /ecommerce/io/v1/sessions` endpoint handler
- Added `POST /ecommerce/io/v1/sessions route`
> [IOBP-520] Add eCommerce session token route

- src/features/wallet/payloads/paymentMethods.ts
This PR sets the remote URI for PayPal payment method
- Added an URI to the PayPal asset from the onboardable payment methods list
> chore: [IOBP-584] Added dynamic asset for paypal payment method

- src/features/wallet/routers/payment.ts
Include a summary of the changes.
- Feature A
- Feature B
Describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
> fix: user wallets ecommerce endpoint

- src/features/services/payloads/get-featured-services.ts
This PR makes CGN special service always visible, to be tappable during CGN e2e tests.
> chore: make CGN special service always visible

- assets/wallet/wallet_payment.html
This PR adds missing outcome inside the payments dropdown webview
- Added outcome 18 and 19 from outcome dropdown list
Test the presence of the outcome 18 and 19 with this PR: https://github.com/pagopa/io-app/pull/6107
> chore: [IOBP-921] Added missing outcome into payments dropdown webview

- assets/yaml/content.yaml
- package.json
- src/payloads/backend.ts
Add `cieid` as `idp` in definitions file and add `feedback_banner_visible: true` in backend.ts (was missing value after last io-services-metadata update) 
- Run io-app using local enviornment 
- check if the application starts and works correctly
> [IOPID-2137] Update definitions

- assets/wallet/wallet_onboarding.html
This PR adds two outcomes inside the webpage of payment onboarding flow.
- Added `PSP_ERROR_ONBOARDING` and `BE_KO` inside the dropdown list.
> chore: [IOBP-1044] Add outcome `PSP_ERROR_ONBOARDING` and `BE_KO` payment onboarding 

- assets/assistanceTools/payments/zendeskOutcomeMapping.json
- assets/assistanceTools/zendesk.json
- src/routers/services_metadata.ts
> [!WARNING]
> This PR depends on https://github.com/pagopa/io-services-metadata/pull/905 
This PR align dev server `json` file for assistance to `io-service-metadata` repo
> refactor: Align tags with metadata repo

- assets/contextual_help/data.json
Align contextual_help `data.json` file to as defined in `io-service-metadata` repo
> chore: update contextual_help data.json

- assets/yaml/content.yaml
- package.json
- src/payloads/backend.ts
> [!Warning]
> This PR depends on https://github.com/pagopa/io-services-metadata/pull/916
> [!Note]
> Need to edit `content_specs` ref on `pakage.json` after merge on `io-services-metadata`
Integrate remote portal URL and edit typo on intesiid name 
Run the application using the local .env and, using proxyman, check whether the values arrive as expected
> chore: [IOPID-2580] add management of remote portal urls

- package.json
- src/payloads/features/cgn/merchants.ts
> feat: [PE-882] Add new discounts number

- assets/CdcSwagger.yml
- package.json
- src/payloads/backend.ts
This PR adds the remote configuration for IOMarkdown
> [IOCOM-2071] Remote configuration for IOMarkdown

- package.json
- src/payloads/backend.ts
> [!note]
> Depends on pagopa/io-services-metadata#928
This PR adds the remote config specified in pagopa/io-services-metadata#928
> feat: App feedback remote config

- scripts/generate-api-models.sh
- src/payloads/backend.ts
> feat:[IOCOM-2205] addition of pn service ID to BE payload

- scripts/generate-api-models.sh
- src/payloads/backend.ts
addition of said URLs
- io-serv-metadata version bump
- backend payload update
tests should pass
> feat: [IOCOM-2185] SEND privacy urls in backend payload

- src/routers/misc.ts
This PR updates the connectivity check endpoint
> [IOPLT-1074] updates connectivity ping endpoint

- src/payloads/backend.ts
IOMarkdown min app version to 3.0.0.0
- Feature A
- Feature B
Describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
> chore: sets IOMarkdown as default

- assets/contextual_help/data.json
This PR align payments FAQ to `io-services-metadata` json file
- Aligned FAQ as defined here https://github.com/pagopa/io-services-metadata
N/A
> chore: align faq to `io-services-metadata`

- src/payloads/backend.ts
This PR updates SEND AAR QRCode regex to support login.notifichedigitali.it domains
- Regex updates to remote config
CI should succeed.
> feat: [IOCOM-2517] Update SEND AAR QRCode regex

- scripts/generate-api-models.sh
- src/payloads/backend.ts
> [!warning]
> This PR depends on https://github.com/pagopa/io-services-metadata/pull/1015
This PR adds the `show_cgn_categories_modal` remote FF
- Added `show_cgn_categories_modal` FF to `backend.ts`
- Run `yarn generate`
- Run `yarn tsc:noemit`
- Ensure no errors are reported
> chore: [IOBP-1926] Add `show_cgn_categories_modal` FF

- src/config.ts
- src/features/messages/routers/ioSendRouter.ts
- src/features/messages/services/ioSendService.ts
- src/features/pn/models/AAR.ts
- src/features/pn/repositories/aarRepository.ts
- src/features/pn/routers/aarRouter.ts
- src/features/pn/services/aarService.ts
- src/features/pn/types/sendConfig.ts
This PR removes the ToS implementation from the AAR SEND flow.
- IO ToS endpoint and SEND ToS endpoint removed
CI should succeed.
> feat: [IOCOM-2556] Remove ToS from SEND

- scripts/generate-api-models.sh
- src/payloads/backend.ts
This pull request added the minimum version for the AAR feature
- Minimum version for the AAR feature
> feat: [IOCOM-2543] feature AAR min version

- src/payloads/backend.ts
updated said regex, to match new specifications
see descriptions 
automated tests should pass
> [IOCOM-2575] updated AAR QR code RegEx

- src/payloads/backend.ts
updated said regex to allow for local testing
automated tests should pass
> [IOCOM-2544] AAR Regex update

- assets/html/login.html
> [!Warning] 
> This PR is related to https://github.com/pagopa/io-app/pull/7340
In this PR, the error code relating to logging in to an active session with a different fiscal code has been changed. The error now has the code 1004.
> chore [IOPID-3332]: change error code name
